In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [5]:
res = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0]
df = pd.read_html(str(table))[0]
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [14]:
df_noDup = df.drop_duplicates(subset='Postcode')
df_noDup.set_index('Postcode', inplace = True)

for i in df_noDup.index :
    Neighbourhood_list = df[df['Postcode']== i ]['Neighbourhood'].tolist()
    df_noDup.at[i, 'Neighbourhood'] =  ','.join(Neighbourhood_list)

##  Ignore cells with a borough that is Not assigned.
df_noDup.reset_index(inplace = True)
df_re = df_noDup.drop(df_noDup[df_noDup['Borough'] == 'Not assigned'].index, axis = 0)

## Assign Borough to 'Not assigned' Neighbourhood
df_re['Neighbourhood'] = df_re['Neighbourhood'].replace('Not assigned', np.nan)
df_re.Neighbourhood.fillna(df_re.Borough, inplace = True)

df_re.reset_index(inplace = True)
df_re.drop("index", axis =1, inplace = True)
print (df_re.shape)
df_re.head(10)

(103, 3)

  Postcode           Borough                    Neighbourhood
0      M3A        North York                        Parkwoods
1      M4A        North York                 Victoria Village
2      M5A  Downtown Toronto         Harbourfront,Regent Park
3      M6A        North York  Lawrence Heights,Lawrence Manor
4      M7A      Queen's Park                     Queen's Park
5      M9A         Etobicoke                 Islington Avenue
6      M1B       Scarborough                    Rouge,Malvern
7      M3B        North York                  Don Mills North
8      M4B         East York   Woodbine Gardens,Parkview Hill
9      M5B  Downtown Toronto          Ryerson,Garden District